"""Backend generators for HUD-style mobility simulation experiments."""

from .generators import (
    CarState,
    CnnFeatureConfig,
    DemandGenerator,
    DispatchAssignment,
    GreedyDispatcher,
    GridSpec,
    GridRouter,
    PeopleGenerator,
    PersonRequest,
    RouteResult,
    TrafficGenerator,
    WorldGenerators,
    build_cnn_feature_channels,
    build_cnn_training_examples,
    build_car_grid,
    build_global_state_for_agent,
    build_mobility_agent_state,
    build_people_grid,
    candidate_next_cells,
    greedy_next_cell_for_car,
    local_patch_from_channels,
)

__all__ = [
    "CarState",
    "CnnFeatureConfig",
    "DemandGenerator",
    "DispatchAssignment",
    "GreedyDispatcher",
    "GridSpec",
    "GridRouter",
    "PeopleGenerator",
    "PersonRequest",
    "RouteResult",
    "TrafficGenerator",
    "WorldGenerators",
    "build_cnn_feature_channels",
    "build_cnn_training_examples",
    "build_car_grid",
    "build_global_state_for_agent",
    "build_mobility_agent_state",
    "build_people_grid",
    "candidate_next_cells",
    "greedy_next_cell_for_car",
    "local_patch_from_channels",
]
